[package]
name = "velo402"
edition = "2024.beta"
license = "Apache-2.0"
authors = ["Velo402 Team"]

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet" }

[addresses]
velo402 = "0x0"
